# Generated by Django 4.1.7 on 2023-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='articles', to='articles.tag', verbose_name='Тэги'),
        ),
    ]
