# Generated by Django 4.1.7 on 2023-03-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
    ]
